export const assets = {
  // bitcoin: {
  //   name: 'bitcoin',
  //   label: 'Bitcoin',
  //   ticker: 'BTC',
  //   webSocketTicker: 'btc',
  // },
  ethereum: {
    name: 'ethereum',
    label: 'Ethereum',
    ticker: 'ETH',
    webSocketTicker: 'eth',
    chainId: 1,
    mainnet: 'https://mainnet.infura.io/v3/0c5409f01bb944168d3bb4b03a674f15',
    apiUrl: 'https://api.etherscan.io/api',
  },
  fantom: {
    name: 'fantom',
    label: 'Fantom',
    ticker: 'FTM',
    webSocketTicker: 'ftm',
    chainId: 250,
    mainnet: 'https://rpc.ankr.com/fantom',
    apiUrl: 'https://api.ftmscan.com/api',
  },
  matic: {
    name: 'matic',
    label: 'Matic',
    ticker: 'MATIC',
    webSocketTicker: 'matic',
    chainId: 137,
    mainnet: 'https://rpc.ankr.com/polygon',
    apiUrl: 'https://api.polygonscan.com/api',
  },
  // avalanche: {
  //   name: 'avalanche',
  //   label: 'Avalanche C-Chain',
  //   ticker: 'AVAX',
  //   webSocketTicker: 'avax',
  //   chainId: 43114,
  //   mainnet: 'https://rpc.ankr.com/avalanche',
  //   apiUrl: 'https://api.avax.network/api',
  // },
};
